version: '3.8'
services:
  python-app:
    build:
      context: https://github.com/etklam/pyrunner.git
      dockerfile: Dockerfile
    container_name: python-app
    ports:
      - "5000:5000"
    
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Shanghai
    

    command: flask run --host=0.0.0.0 --port=5000
    
    restart: unless-stopped